### ISSUE TITLE
One Step Checkout servicepoints JS error - order servicepoint information missing

### ISSUE THREAD

**Issue by pimruiter** [creative-ict/sendcloud#2]
Hi Creative ICT,

The following javascript error is visible when opening the checkout of the supported Magento2 One Step Checkout extension.

![image](https://user-images.githubusercontent.com/16269189/48776770-ff935b00-ecd0-11e8-8dc0-ecb958d6d6fe.png)

This doesn’t break the checkout, but after saving the order, the servicepoint location is not saved in the order. You’ll see an empty location in the Magento2 backend with the order. Also no servicepoint is created in Sendcloud.

I am using MG2 v2.2.5 and PHP 7.1.18
Module version 1.0.7

**Comment by pimkorschnercreative** [comment]
Hi Pim,

We are currently working on the issues within this project. Your pull request will be checked by our developers working on the project.

**Comment by pimkorschnercreative** [comment]
We cannot seem to replicate the issue on our side. 
Could you please provide some additional information with the steps to reproduce this issue and which of the supported Magento2 One Step Checkout extensions you are using?

As for pull request #4, triggering a click on the first shipping method does not seem like a proper solution to the issue. The issue is getServicePointInformation() returning null. Which probably means servicePointObject in  sendcloud/view/frontend/web/js/view/checkout/shipping/servicePoint.js
is null. 

For now, I'll merge pull request #5 into a feature branch which you'll then be able to require with composer.
